export const foods = [
  {
    id: 'oats',
    name: '燕麦',
    category: 'breakfast',
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    unit: 'g',
    defaultPortion: 45,
    tags: ['高纤维', '主食'],
  },
  {
    id: 'egg',
    name: '鸡蛋',
    category: 'breakfast',
    calories: 143,
    protein: 12.6,
    carbs: 0.7,
    fat: 9.5,
    unit: 'g',
    defaultPortion: 60,
    tags: ['优质蛋白'],
  },
  {
    id: 'milk-lowfat',
    name: '低脂牛奶',
    category: 'breakfast',
    calories: 46,
    protein: 3.4,
    carbs: 5,
    fat: 1.5,
    unit: 'ml',
    defaultPortion: 250,
    tags: ['乳制品'],
  },
  {
    id: 'soy-milk',
    name: '无糖豆浆',
    category: 'breakfast',
    calories: 33,
    protein: 3,
    carbs: 1.8,
    fat: 1.6,
    unit: 'ml',
    defaultPortion: 300,
    tags: ['植物蛋白'],
  },
  {
    id: 'whole-wheat-bread',
    name: '全麦面包',
    category: 'breakfast',
    calories: 246,
    protein: 9,
    carbs: 41,
    fat: 4.2,
    unit: 'g',
    defaultPortion: 70,
    tags: ['主食', '高纤维'],
  },
  {
    id: 'purple-sweet-potato',
    name: '紫薯',
    category: 'breakfast',
    calories: 106,
    protein: 1.6,
    carbs: 25.1,
    fat: 0.2,
    unit: 'g',
    defaultPortion: 150,
    tags: ['主食', '饱腹'],
  },
  {
    id: 'corn',
    name: '玉米',
    category: 'breakfast',
    calories: 112,
    protein: 4,
    carbs: 22.8,
    fat: 1.2,
    unit: 'g',
    defaultPortion: 160,
    tags: ['主食', '粗粮'],
  },
  {
    id: 'greek-yogurt',
    name: '希腊酸奶',
    category: 'breakfast',
    calories: 73,
    protein: 9,
    carbs: 3.6,
    fat: 2,
    unit: 'g',
    defaultPortion: 180,
    tags: ['高蛋白'],
  },
  {
    id: 'chicken-breast',
    name: '鸡胸肉',
    category: 'lunch',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    unit: 'g',
    defaultPortion: 130,
    tags: ['高蛋白', '低脂'],
  },
  {
    id: 'brown-rice',
    name: '糙米饭',
    category: 'lunch',
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    unit: 'g',
    defaultPortion: 160,
    tags: ['主食', '粗粮'],
  },
  {
    id: 'buckwheat-noodle',
    name: '荞麦面',
    category: 'lunch',
    calories: 99,
    protein: 5.1,
    carbs: 21.4,
    fat: 0.1,
    unit: 'g',
    defaultPortion: 170,
    tags: ['主食', '低脂'],
  },
  {
    id: 'tofu-firm',
    name: '北豆腐',
    category: 'lunch',
    calories: 81,
    protein: 8.1,
    carbs: 4.2,
    fat: 3.7,
    unit: 'g',
    defaultPortion: 160,
    tags: ['植物蛋白'],
  },
  {
    id: 'beef-lean',
    name: '瘦牛肉',
    category: 'lunch',
    calories: 125,
    protein: 20.2,
    carbs: 0,
    fat: 4.2,
    unit: 'g',
    defaultPortion: 120,
    tags: ['高蛋白', '铁'],
  },
  {
    id: 'shrimp',
    name: '虾仁',
    category: 'lunch',
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    unit: 'g',
    defaultPortion: 130,
    tags: ['高蛋白', '低脂'],
  },
  {
    id: 'broccoli',
    name: '西兰花',
    category: 'lunch',
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    unit: 'g',
    defaultPortion: 180,
    tags: ['蔬菜', '高纤维'],
  },
  {
    id: 'spinach',
    name: '菠菜',
    category: 'lunch',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    unit: 'g',
    defaultPortion: 180,
    tags: ['蔬菜'],
  },
  {
    id: 'tomato',
    name: '番茄',
    category: 'lunch',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    unit: 'g',
    defaultPortion: 180,
    tags: ['蔬菜'],
  },
  {
    id: 'salmon',
    name: '三文鱼',
    category: 'dinner',
    calories: 208,
    protein: 20.4,
    carbs: 0,
    fat: 13.4,
    unit: 'g',
    defaultPortion: 110,
    tags: ['优质脂肪', '高蛋白'],
  },
  {
    id: 'cod',
    name: '鳕鱼',
    category: 'dinner',
    calories: 82,
    protein: 17.8,
    carbs: 0,
    fat: 0.7,
    unit: 'g',
    defaultPortion: 150,
    tags: ['低脂', '高蛋白'],
  },
  {
    id: 'turkey',
    name: '火鸡胸',
    category: 'dinner',
    calories: 135,
    protein: 29,
    carbs: 0,
    fat: 1,
    unit: 'g',
    defaultPortion: 120,
    tags: ['低脂', '高蛋白'],
  },
  {
    id: 'millet-porridge',
    name: '小米粥',
    category: 'dinner',
    calories: 46,
    protein: 1.4,
    carbs: 9.7,
    fat: 0.4,
    unit: 'g',
    defaultPortion: 250,
    tags: ['主食', '清淡'],
  },
  {
    id: 'sweet-potato',
    name: '红薯',
    category: 'dinner',
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    unit: 'g',
    defaultPortion: 180,
    tags: ['主食', '饱腹'],
  },
  {
    id: 'quinoa',
    name: '藜麦饭',
    category: 'dinner',
    calories: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    unit: 'g',
    defaultPortion: 150,
    tags: ['主食', '植物蛋白'],
  },
  {
    id: 'bok-choy',
    name: '小青菜',
    category: 'dinner',
    calories: 15,
    protein: 1.5,
    carbs: 2.2,
    fat: 0.2,
    unit: 'g',
    defaultPortion: 200,
    tags: ['蔬菜', '低热量'],
  },
  {
    id: 'mushroom',
    name: '香菇',
    category: 'dinner',
    calories: 26,
    protein: 2.2,
    carbs: 5.2,
    fat: 0.3,
    unit: 'g',
    defaultPortion: 140,
    tags: ['蔬菜', '鲜味'],
  },
  {
    id: 'cucumber',
    name: '黄瓜',
    category: 'snack',
    calories: 16,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    unit: 'g',
    defaultPortion: 180,
    tags: ['低热量', '蔬菜'],
  },
  {
    id: 'apple',
    name: '苹果',
    category: 'snack',
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    unit: 'g',
    defaultPortion: 180,
    tags: ['水果'],
  },
  {
    id: 'banana',
    name: '香蕉',
    category: 'snack',
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    unit: 'g',
    defaultPortion: 110,
    tags: ['水果', '运动前'],
  },
  {
    id: 'blueberry',
    name: '蓝莓',
    category: 'snack',
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    unit: 'g',
    defaultPortion: 120,
    tags: ['水果'],
  },
  {
    id: 'almond',
    name: '杏仁',
    category: 'snack',
    calories: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    unit: 'g',
    defaultPortion: 15,
    tags: ['坚果', '优质脂肪'],
  },
  {
    id: 'edamame',
    name: '毛豆',
    category: 'snack',
    calories: 121,
    protein: 11.9,
    carbs: 8.9,
    fat: 5.2,
    unit: 'g',
    defaultPortion: 120,
    tags: ['植物蛋白', '高纤维'],
  },
  {
    id: 'protein-milk',
    name: '高蛋白牛奶',
    category: 'snack',
    calories: 62,
    protein: 6,
    carbs: 4,
    fat: 2,
    unit: 'ml',
    defaultPortion: 250,
    tags: ['高蛋白'],
  },
  {
    id: 'konjac',
    name: '魔芋结',
    category: 'snack',
    calories: 10,
    protein: 0.2,
    carbs: 2.3,
    fat: 0,
    unit: 'g',
    defaultPortion: 180,
    tags: ['低热量', '饱腹'],
  },
  {
    id: 'chicken-leg-skinless',
    name: '去皮鸡腿肉',
    category: 'dinner',
    calories: 159,
    protein: 24,
    carbs: 0,
    fat: 6.6,
    unit: 'g',
    defaultPortion: 130,
    tags: ['高蛋白'],
  },
  {
    id: 'pumpkin',
    name: '南瓜',
    category: 'dinner',
    calories: 26,
    protein: 1,
    carbs: 6.5,
    fat: 0.1,
    unit: 'g',
    defaultPortion: 220,
    tags: ['主食', '低热量'],
  },
  {
    id: 'black-rice',
    name: '黑米饭',
    category: 'lunch',
    calories: 116,
    protein: 3.1,
    carbs: 24.2,
    fat: 0.8,
    unit: 'g',
    defaultPortion: 150,
    tags: ['主食', '粗粮'],
  },
]

export const foodCategories = {
  breakfast: '早餐',
  lunch: '午餐',
  dinner: '晚餐',
  snack: '加餐',
}
