export const foods = [
  {
    id: 'chicken-breast',
    name: '鸡胸肉',
    category: 'protein',
    per100g: { calories: 120, protein: 23, carbs: 0, fat: 2 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 120,
    tags: ['高蛋白', '低脂'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'chicken-leg-skinless',
    name: '去皮鸡腿肉',
    category: 'protein',
    per100g: { calories: 150, protein: 19, carbs: 0, fat: 8 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 120,
    tags: ['高蛋白'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'egg',
    name: '鸡蛋',
    category: 'protein',
    per100g: { calories: 143, protein: 13, carbs: 1.1, fat: 9.5 },
    mealFit: ['breakfast', 'lunch', 'dinner', 'snack'],
    unit: 'g',
    defaultPortion: 50,
    tags: ['优质蛋白'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'shrimp',
    name: '虾仁',
    category: 'protein',
    per100g: { calories: 99, protein: 24, carbs: 0.2, fat: 0.3 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 80,
    tags: ['高蛋白', '低脂'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'cod',
    name: '鳕鱼',
    category: 'protein',
    per100g: { calories: 82, protein: 18, carbs: 0, fat: 0.7 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['低脂', '高蛋白'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'salmon',
    name: '三文鱼',
    category: 'protein',
    per100g: { calories: 208, protein: 20, carbs: 0, fat: 13 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 80,
    tags: ['优质脂肪', '高蛋白'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'beef-lean',
    name: '瘦牛肉',
    category: 'protein',
    per100g: { calories: 170, protein: 26, carbs: 0, fat: 7 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['高蛋白', '铁'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'pork-tenderloin',
    name: '猪里脊',
    category: 'protein',
    per100g: { calories: 143, protein: 21, carbs: 0, fat: 6 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['高蛋白'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'tofu-firm',
    name: '北豆腐',
    category: 'protein',
    per100g: { calories: 76, protein: 8, carbs: 1.9, fat: 4.8 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['植物蛋白'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'dried-tofu',
    name: '豆干',
    category: 'protein',
    per100g: { calories: 160, protein: 16, carbs: 6, fat: 8 },
    mealFit: ['lunch', 'dinner', 'snack'],
    unit: 'g',
    defaultPortion: 50,
    tags: ['植物蛋白'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'edamame',
    name: '毛豆',
    category: 'protein',
    per100g: { calories: 121, protein: 11, carbs: 8.9, fat: 5.2 },
    mealFit: ['lunch', 'dinner', 'snack'],
    unit: 'g',
    defaultPortion: 50,
    tags: ['植物蛋白', '高纤维'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'tuna-canned',
    name: '水浸金枪鱼',
    category: 'protein',
    per100g: { calories: 116, protein: 26, carbs: 0, fat: 1 },
    mealFit: ['lunch', 'dinner', 'snack'],
    unit: 'g',
    defaultPortion: 50,
    tags: ['高蛋白', '低脂'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'rice',
    name: '米饭',
    category: 'carb',
    per100g: { calories: 130, protein: 2.7, carbs: 28.2, fat: 0.3 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['主食'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'brown-rice',
    name: '糙米饭',
    category: 'carb',
    per100g: { calories: 123, protein: 2.7, carbs: 25.6, fat: 1 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['主食', '粗粮'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'oats',
    name: '燕麦',
    category: 'carb',
    per100g: { calories: 389, protein: 16.9, carbs: 66.3, fat: 6.9 },
    mealFit: ['breakfast'],
    unit: 'g',
    defaultPortion: 45,
    tags: ['高纤维', '主食'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'sweet-potato',
    name: '红薯',
    category: 'carb',
    per100g: { calories: 86, protein: 1.6, carbs: 20.1, fat: 0.1 },
    mealFit: ['breakfast', 'lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['主食', '饱腹'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'purple-sweet-potato',
    name: '紫薯',
    category: 'carb',
    per100g: { calories: 90, protein: 1.8, carbs: 21, fat: 0.1 },
    mealFit: ['breakfast', 'lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['主食', '饱腹'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'potato',
    name: '土豆',
    category: 'carb',
    per100g: { calories: 77, protein: 2, carbs: 17.5, fat: 0.1 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['主食'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'corn',
    name: '玉米',
    category: 'carb',
    per100g: { calories: 96, protein: 3.4, carbs: 21, fat: 1.5 },
    mealFit: ['breakfast', 'lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['主食', '粗粮'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'whole-wheat-bread',
    name: '全麦面包',
    category: 'carb',
    per100g: { calories: 247, protein: 13, carbs: 41, fat: 4.2 },
    mealFit: ['breakfast', 'snack'],
    unit: 'g',
    defaultPortion: 60,
    tags: ['主食', '高纤维'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'buckwheat-noodle',
    name: '荞麦面',
    category: 'carb',
    per100g: { calories: 99, protein: 5, carbs: 21, fat: 0.1 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['主食', '低脂'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'pasta',
    name: '意面',
    category: 'carb',
    per100g: { calories: 158, protein: 5.8, carbs: 30.9, fat: 0.9 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['主食'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'quinoa',
    name: '藜麦饭',
    category: 'carb',
    per100g: { calories: 120, protein: 4.4, carbs: 21.3, fat: 1.9 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['主食', '植物蛋白'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'broccoli',
    name: '西兰花',
    category: 'vegetable',
    per100g: { calories: 34, protein: 2.8, carbs: 6.6, fat: 0.4 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['蔬菜', '高纤维'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'lettuce',
    name: '生菜',
    category: 'vegetable',
    per100g: { calories: 15, protein: 1.4, carbs: 2.9, fat: 0.2 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 80,
    tags: ['蔬菜'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'spinach',
    name: '菠菜',
    category: 'vegetable',
    per100g: { calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['蔬菜'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'youmaicai',
    name: '油麦菜',
    category: 'vegetable',
    per100g: { calories: 16, protein: 1.4, carbs: 3.3, fat: 0.2 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 80,
    tags: ['蔬菜'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'baby-bok-choy',
    name: '娃娃菜',
    category: 'vegetable',
    per100g: { calories: 13, protein: 1.2, carbs: 2.4, fat: 0.2 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['蔬菜'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'tomato',
    name: '番茄',
    category: 'vegetable',
    per100g: { calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
    mealFit: ['breakfast', 'lunch', 'dinner', 'snack'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['蔬菜'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'cucumber',
    name: '黄瓜',
    category: 'vegetable',
    per100g: { calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1 },
    mealFit: ['lunch', 'dinner', 'snack'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['低热量', '蔬菜'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'carrot',
    name: '胡萝卜',
    category: 'vegetable',
    per100g: { calories: 41, protein: 0.9, carbs: 9.6, fat: 0.2 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 80,
    tags: ['蔬菜'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'mushroom',
    name: '香菇',
    category: 'vegetable',
    per100g: { calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 80,
    tags: ['蔬菜', '鲜味'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'enoki',
    name: '金针菇',
    category: 'vegetable',
    per100g: { calories: 37, protein: 2.7, carbs: 7.8, fat: 0.3 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 80,
    tags: ['蔬菜'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'bell-pepper',
    name: '彩椒',
    category: 'vegetable',
    per100g: { calories: 31, protein: 1, carbs: 6, fat: 0.3 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 80,
    tags: ['蔬菜'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'asparagus',
    name: '芦笋',
    category: 'vegetable',
    per100g: { calories: 20, protein: 2.2, carbs: 3.9, fat: 0.1 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 80,
    tags: ['蔬菜'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'winter-melon',
    name: '冬瓜',
    category: 'vegetable',
    per100g: { calories: 13, protein: 0.4, carbs: 3, fat: 0.2 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['蔬菜', '低热量'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'seaweed',
    name: '海带',
    category: 'vegetable',
    per100g: { calories: 43, protein: 1.7, carbs: 9.6, fat: 0.6 },
    mealFit: ['lunch', 'dinner'],
    unit: 'g',
    defaultPortion: 20,
    tags: ['蔬菜'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'apple',
    name: '苹果',
    category: 'fruit',
    per100g: { calories: 52, protein: 0.3, carbs: 13.8, fat: 0.2 },
    mealFit: ['breakfast', 'snack'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['水果'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'banana',
    name: '香蕉',
    category: 'fruit',
    per100g: { calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3 },
    mealFit: ['breakfast', 'snack'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['水果', '运动前'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'blueberry',
    name: '蓝莓',
    category: 'fruit',
    per100g: { calories: 57, protein: 0.7, carbs: 14.5, fat: 0.3 },
    mealFit: ['breakfast', 'snack'],
    unit: 'g',
    defaultPortion: 50,
    tags: ['水果'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'strawberry',
    name: '草莓',
    category: 'fruit',
    per100g: { calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3 },
    mealFit: ['breakfast', 'snack'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['水果'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'orange',
    name: '橙子',
    category: 'fruit',
    per100g: { calories: 47, protein: 0.9, carbs: 11.8, fat: 0.1 },
    mealFit: ['snack'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['水果'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'kiwi',
    name: '猕猴桃',
    category: 'fruit',
    per100g: { calories: 61, protein: 1.1, carbs: 14.7, fat: 0.5 },
    mealFit: ['breakfast', 'snack'],
    unit: 'g',
    defaultPortion: 80,
    tags: ['水果'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'pear',
    name: '梨',
    category: 'fruit',
    per100g: { calories: 57, protein: 0.4, carbs: 15.2, fat: 0.1 },
    mealFit: ['snack'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['水果'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'yogurt-plain',
    name: '无糖酸奶',
    category: 'dairy',
    per100g: { calories: 61, protein: 3.5, carbs: 4.7, fat: 3.3 },
    mealFit: ['breakfast', 'snack'],
    unit: 'g',
    defaultPortion: 150,
    tags: ['乳制品'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'greek-yogurt',
    name: '希腊酸奶',
    category: 'dairy',
    per100g: { calories: 73, protein: 10, carbs: 3.9, fat: 1.9 },
    mealFit: ['breakfast', 'snack'],
    unit: 'g',
    defaultPortion: 100,
    tags: ['高蛋白'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'milk-lowfat',
    name: '低脂牛奶',
    category: 'dairy',
    per100g: { calories: 42, protein: 3.4, carbs: 5, fat: 1 },
    mealFit: ['breakfast', 'snack'],
    unit: 'ml',
    defaultPortion: 200,
    tags: ['乳制品'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'soy-milk',
    name: '无糖豆浆',
    category: 'dairy',
    per100g: { calories: 33, protein: 3, carbs: 1.6, fat: 1.8 },
    mealFit: ['breakfast', 'snack'],
    unit: 'ml',
    defaultPortion: 200,
    tags: ['植物蛋白'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'cheese-lowfat',
    name: '低脂奶酪',
    category: 'dairy',
    per100g: { calories: 173, protein: 24, carbs: 3, fat: 7 },
    mealFit: ['breakfast', 'snack'],
    unit: 'g',
    defaultPortion: 30,
    tags: ['乳制品'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'olive-oil',
    name: '橄榄油',
    category: 'fat',
    per100g: { calories: 884, protein: 0, carbs: 0, fat: 100 },
    mealFit: ['lunch', 'dinner', 'snack'],
    unit: 'ml',
    defaultPortion: 10,
    tags: ['优质脂肪'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'avocado',
    name: '牛油果',
    category: 'fat',
    per100g: { calories: 160, protein: 2, carbs: 8.5, fat: 14.7 },
    mealFit: ['breakfast', 'lunch', 'snack'],
    unit: 'g',
    defaultPortion: 50,
    tags: ['优质脂肪'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'almond',
    name: '杏仁',
    category: 'fat',
    per100g: { calories: 579, protein: 21, carbs: 21.6, fat: 49.9 },
    mealFit: ['snack'],
    unit: 'g',
    defaultPortion: 20,
    tags: ['坚果', '优质脂肪'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'walnut',
    name: '核桃',
    category: 'fat',
    per100g: { calories: 654, protein: 15.2, carbs: 13.7, fat: 65.2 },
    mealFit: ['snack'],
    unit: 'g',
    defaultPortion: 15,
    tags: ['坚果', '优质脂肪'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'peanut-butter',
    name: '花生酱',
    category: 'fat',
    per100g: { calories: 588, protein: 25, carbs: 20, fat: 50 },
    mealFit: ['breakfast', 'snack'],
    unit: 'g',
    defaultPortion: 15,
    tags: ['坚果'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'sesame-paste',
    name: '芝麻酱',
    category: 'fat',
    per100g: { calories: 595, protein: 17, carbs: 21, fat: 53 },
    mealFit: ['lunch', 'dinner', 'snack'],
    unit: 'g',
    defaultPortion: 10,
    tags: ['优质脂肪'],
    source: 'default',
    scenario: 'home',
  },
  {
    id: 'chia-seed',
    name: '奇亚籽',
    category: 'fat',
    per100g: { calories: 486, protein: 16.5, carbs: 42.1, fat: 30.7 },
    mealFit: ['breakfast', 'snack'],
    unit: 'g',
    defaultPortion: 10,
    tags: ['优质脂肪'],
    source: 'default',
    scenario: 'home',
  },
]
