export const MEAL_TEMPLATES = [
  {
    id: 'protein-oat-bowl',
    mealType: 'breakfast',
    scenario: 'home',
    slots: [
      { category: 'dairy', required: true, fallback: 'dairy' },
      { category: 'carb', required: true },
      { category: 'fruit', required: false },
      { category: 'fat', required: false },
    ],
    cookingMethod: 'mix',
    namePattern: '{fruit}{dairy}{carb}',
    simpleStepPattern: '将{nameList}搅拌混合即可。',
    tags: ['快手', '高蛋白'],
  },
  {
    id: 'egg-staple-breakfast',
    mealType: 'breakfast',
    scenario: 'home',
    slots: [
      { category: 'protein', required: true },
      { category: 'carb', required: true },
      { category: 'fruit', required: false },
      { category: 'vegetable', required: false },
    ],
    cookingMethod: 'pan_fry',
    namePattern: '{protein}{carb}{vegetable}',
    simpleStepPattern: '{protein}煎熟，搭配{carb}和{vegetable}即可。',
    tags: ['快手', '饱腹'],
  },
  {
    id: 'yogurt-fruit-bowl',
    mealType: 'breakfast',
    scenario: 'home',
    slots: [
      { category: 'dairy', required: true },
      { category: 'fruit', required: true },
      { category: 'carb', required: false },
      { category: 'fat', required: false },
    ],
    cookingMethod: 'mix',
    namePattern: '{fruit}{dairy}{carb}',
    simpleStepPattern: '{dairy}中加入{fruit}和{carb}，拌匀即可。',
    tags: ['快手', '清爽'],
  },
  {
    id: 'soymilk-toast-breakfast',
    mealType: 'breakfast',
    scenario: 'home',
    slots: [
      { category: 'dairy', required: true },
      { category: 'carb', required: true },
      { category: 'fruit', required: false },
    ],
    cookingMethod: 'assemble',
    namePattern: '{dairy}{carb}{fruit}',
    simpleStepPattern: '{dairy}搭配{carb}和{fruit}，简单一餐。',
    tags: ['快手', '清淡'],
  },
  {
    id: 'protein-bowl',
    mealType: 'main',
    scenario: 'home',
    slots: [
      { category: 'protein', required: true },
      { category: 'carb', required: true },
      { category: 'vegetable', required: true },
      { category: 'fat', required: false },
    ],
    cookingMethod: 'boil',
    namePattern: '{protein}{vegetable}{carb}',
    simpleStepPattern: '{protein}和{vegetable}处理熟，搭配{carb}即可。',
    tags: ['自炊', '均衡'],
  },
  {
    id: 'stir-fry-rice',
    mealType: 'main',
    scenario: 'home',
    slots: [
      { category: 'protein', required: true },
      { category: 'vegetable', required: true },
      { category: 'carb', required: true },
      { category: 'fat', required: true },
    ],
    cookingMethod: 'stir_fry',
    namePattern: '{protein}{vegetable}饭',
    simpleStepPattern: '{protein}和{vegetable}翻炒至熟，搭配{carb}即可。',
    tags: ['自炊', '中式'],
  },
  {
    id: 'noodle-bowl',
    mealType: 'main',
    scenario: 'home',
    slots: [
      { category: 'protein', required: true },
      { category: 'carb', required: true, filter: ['荞麦面', '意面'] },
      { category: 'vegetable', required: true },
    ],
    cookingMethod: 'boil',
    namePattern: '{protein}{vegetable}{carb}',
    simpleStepPattern: '{carb}煮熟，{protein}焯熟，和{vegetable}一同摆盘即可。',
    tags: ['自炊', '快手'],
  },
  {
    id: 'steam-prep-box',
    mealType: 'main',
    scenario: 'home',
    slots: [
      { category: 'protein', required: true },
      { category: 'carb', required: true },
      { category: 'vegetable', required: true },
    ],
    cookingMethod: 'steam',
    namePattern: '{protein}{vegetable}{carb}',
    simpleStepPattern: '{protein}和{vegetable}蒸熟，搭配{carb}即可。',
    tags: ['自炊', '备餐'],
  },
  {
    id: 'tofu-veggie-rice',
    mealType: 'main',
    scenario: 'home',
    slots: [
      { category: 'protein', required: true, filter: ['豆腐', '豆干', '毛豆'] },
      { category: 'vegetable', required: true },
      { category: 'carb', required: true },
    ],
    cookingMethod: 'stir_fry',
    namePattern: '{protein}{vegetable}{carb}',
    simpleStepPattern: '{protein}和{vegetable}煸炒调味，搭配{carb}。',
    tags: ['自炊', '素食'],
  },
  {
    id: 'yogurt-fruit-snack',
    mealType: 'snack',
    scenario: 'home',
    slots: [
      { category: 'dairy', required: true },
      { category: 'fruit', required: true },
    ],
    cookingMethod: 'mix',
    namePattern: '{fruit}{dairy}',
    simpleStepPattern: '{dairy}盛碗，加入{fruit}即可。',
    tags: ['快手', '清爽'],
  },
  {
    id: 'egg-fruit-snack',
    mealType: 'snack',
    scenario: 'home',
    slots: [
      { category: 'protein', required: true },
      { category: 'fruit', required: false },
    ],
    cookingMethod: 'boil',
    namePattern: '{protein}{fruit}',
    simpleStepPattern: '{protein}煮熟，搭配{fruit}食用。',
    tags: ['快手', '高蛋白'],
  },
  {
    id: 'nut-yogurt-snack',
    mealType: 'snack',
    scenario: 'home',
    slots: [
      { category: 'dairy', required: true },
      { category: 'fat', required: true },
    ],
    cookingMethod: 'mix',
    namePattern: '{dairy}{fat}',
    simpleStepPattern: '{dairy}中加入{fat}，拌匀即可。',
    tags: ['快手', '饱腹'],
  },
  {
    id: 'protein-bite',
    mealType: 'snack',
    scenario: 'home',
    slots: [
      { category: 'protein', required: true },
      { category: 'fruit', required: false },
    ],
    cookingMethod: 'assemble',
    namePattern: '{protein}{fruit}',
    simpleStepPattern: '{protein}和{fruit}搭配食用。',
    tags: ['快手', '高蛋白'],
  },
]
