// Re-export bridge: storage adapter now in adapters/storage/
export {
  normalizeProfile,
  loadProfile,
  loadSchedule,
  loadLatestPlan,
  saveProfile,
  saveSchedule,
  saveLatestPlan,
  deleteLatestPlan,
  loadWeightLogs,
  saveWeightLog,
  deleteWeightLog,
  loadCheckins,
  saveCheckin,
  deleteCheckin,
  clearAllData,
  exportAllData,
  importAllData,
  getAppState,
  dualGet,
  dualSet,
  dualDelete,
} from '../adapters/storage/index.js'
